### ISSUE TITLE
unable to click options

### ISSUE THREAD

**Issue by 3r1u5** [algernon-A/ZoningAdjuster#13]
I can't click on any of the zoning options in the panel since the latest update. I can still add/remove zoning by clicking on a road, but I can't choose a priority or force/disable zoning.

**Comment by algernon-A** [comment]
Ouput log and screenshot, please?

**Comment by algernon-A** [comment]
Assuming this is the same issue as reported by some other players who have provided logs, this has now been fixed in 4bc67aba7bd6b536b2a96a91f61dd3cc321bc5f5.

Closing this for now; please log a new issue if the symptoms persist.  Remember, bug reports without supporting info (ouput logs and screenshots) are of little use.
